name: test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: '1.13'
      - run: |
          echo "::add-path::$(go env GOPATH)/bin"
          echo "::set-env name=GOPATH::$(go env GOPATH)"
      - run: make depend
      - run: make test
