name: test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: src/github.com/shogo82148/goa-v1
          persist-credentials: false
      - uses: actions/setup-go@v1
        with:
          go-version: '1.13'
      - run: |
          echo "::add-path::$(go env GOPATH)/bin"
          echo "::set-env name=GOPATH::$(go env GOPATH)"
      - run: make depend
        working-directory: src/github.com/shogo82148/goa-v1
      - run: make test
        working-directory: src/github.com/shogo82148/goa-v1
